spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_app
    username: postgres
    password: feyzafeyza
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect